# Generated by Django 5.0.6 on 2024-05-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puc_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nome',
            field=models.CharField(default='Usuário', max_length=100),
        ),
    ]
